### ISSUE TITLE
Everything is center-justified 

### ISSUE THREAD

**Issue by dylanacious** [denverpost/reverb#3]
Starting around noon today, all text (headline, body, subheads etc.) is inexplicably center-justified

**Comment by freejoe76** [comment]
Example: http://www.heyreverb.com/blog/2016/01/14/janet-jacksons-denver-show-re-rescheduled-for-july/112447/

**Comment by freejoe76** [comment]
This is caused by an ad div that was opened and never closed:

`<div class="adElement clearfloat" id="adPosition1" style="clear:both;text-align:center;">`

**Comment by freejoe76** [comment]
Someone added an extra `</div>` in that pencil ad somewhere. @dylanacious do you know how to get in touch with the ad people?

**Comment by dylanacious** [comment]
Hey! I don't. But if you show me the way, I'll do it.

---

Dylan Owens
The Denver Post / Reverb http://www.heyreverb.com, Editor
(303) 954-1785
f: @heyreverb https://www.facebook.com/heyreverb i: @heyreverb
https://instagram.com/heyreverb/  t: @RVRB https://twitter.com/rvrb

**Comment by freejoe76** [comment]
I don't remember either, which is why I asked you.

**Comment by freejoe76** [comment]
yo check it out it's not happening anymore http://www.heyreverb.com/blog/2016/01/14/janet-jacksons-denver-show-re-rescheduled-for-july/112447/

**Comment by dylanacious** [comment]
woohoo! nice work whoever you are!!!!

---

Dylan Owens
The Denver Post / Reverb http://www.heyreverb.com, Editor
(303) 954-1785
f: @heyreverb https://www.facebook.com/heyreverb i: @heyreverb
https://instagram.com/heyreverb/  t: @RVRB https://twitter.com/rvrb

**Comment by dylanacious** [comment]
Aaand it's back :(

---

Dylan Owens
The Denver Post / Reverb http://www.heyreverb.com, Editor
(303) 954-1785
f: @heyreverb https://www.facebook.com/heyreverb i: @heyreverb
https://instagram.com/heyreverb/  t: @RVRB https://twitter.com/rvrb

**Comment by freejoe76** [comment]
Bummer. I just got the email address we send these issues to and emailed them. You're cc'ed.

**Comment by dylanacious** [comment]
hah, thanks man. Appreciate it.

---

Dylan Owens
The Denver Post / Reverb http://www.heyreverb.com, Editor
(303) 954-1785
f: @heyreverb https://www.facebook.com/heyreverb i: @heyreverb
https://instagram.com/heyreverb/  t: @RVRB https://twitter.com/rvrb
