### ISSUE TITLE
No access to Reverb backend 

### ISSUE THREAD

**Issue by dylanacious** [denverpost/reverb#4]
Attempts to access Reverb's backend are met with a generic "could not retrieve" page. First noticed around 6 a.m. on 05/31/16.

<img width="984" alt="screen shot 2016-05-31 at 6 31 30 am" src="https://cloud.githubusercontent.com/assets/16709532/15674345/69638136-26f9-11e6-83e9-cbf63a8de21e.png">

**Comment by freejoe76** [comment]
Hi Dylan,

This looks like it's working now.
